In [2]:
import notebook_setup

✓ Backend added to Python Path

In [3]:
import pandas as pd

from app.database.database import SessionLocal

db = SessionLocal()

In [4]:
df = pd.read_csv("../dataset/anime.csv")

df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [5]:
df.shape

(12294, 7)

In [6]:
df.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  str
 2   genre     12232 non-null  str
 3   type      12269 non-null  str
 4   episodes  12294 non-null  str
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 1.3 MB

In [8]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [9]:
df.sample(10)

,anime_id,name,genre,type,episodes,rating,members
816,3545,Kochira Katsushikaku Kameari Kouenmae Hashutsu...,"Comedy, Police, Slice of Life",TV,373,7.82,4734
1654,23383,D-Frag! OVA,"Comedy, Game, Seinen",OVA,1,7.47,28116
337,1530,Kanon (2006),"Drama, Romance, Slice of Life, Supernatural",TV,24,8.17,163171
10893,28543,Zukkoke Sannin-gumi no Hi Asobi Boushi Daisakusen,"Drama, Kids",OVA,1,5.83,50
12214,30663,Docchi mo Maid,"Action, Comedy, Ecchi, Yuri",ONA,1,5.15,223
1784,1250,Erementar Gerad,"Adventure, Comedy, Fantasy, Magic, Romance, Su...",TV,26,7.44,63193
6496,31890,Nurse Witch Komugi-chan R,"Comedy, Magic, Parody",TV,12,6.09,7376
6398,32745,Fake Style,Music,Music,1,6.13,85
10005,13103,Ponta to Ensoku,"Adventure, Drama",OVA,1,6.40,185
9168,32832,Kaze no You ni,"Drama, Slice of Life",Movie,1,6.14,741

In [10]:
df["genre"] = df["genre"].fillna("Unknown")
df["type"] = df["type"].fillna("Unknown")
df["rating"] = df["rating"].fillna(0.0)

In [11]:
df["episodes"].unique()[:20]

<ArrowStringArray>
[  '1',  '64',  '51',  '24',  '10', '148', '110',  '13', '201',  '25',  '22',
  '75',   '4',  '26',  '12',  '27',  '43',  '74',  '37',   '2']
Length: 20, dtype: str

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  str
 2   genre     12294 non-null  str
 3   type      12294 non-null  str
 4   episodes  12294 non-null  str
 5   rating    12294 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 1.3 MB

In [13]:
df.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [1]:
import notebook_setup

============================================================
✓ Notebook Environment Ready
Project Root : d:\Anime-Recommendation System\Anime-Recommendation-System
Backend Path : d:\Anime-Recommendation System\Anime-Recommendation-System\backend
============================================================

In [2]:
from notebook_helpers import (
    get_db,
    load_anime_dataset,
    clean_anime_dataset,
    show_dataset_info
)

import pandas as pd

In [3]:
db = get_db()

In [4]:
df = load_anime_dataset()

df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [5]:
df = clean_anime_dataset(df)

In [6]:
show_dataset_info(df)

============================================================
Shape: (12294, 7)
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  str
 2   genre     12294 non-null  str
 3   type      12294 non-null  str
 4   episodes  12294 non-null  int64
 5   rating    12294 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(3), str(3)
memory usage: 1.3 MB
None
============================================================
anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [7]:
all_genres = set()

for genres in df["genre"]:
    for genre in genres.split(","):
        all_genres.add(genre.strip())

print(f"Total Unique Genres: {len(all_genres)}")

Total Unique Genres: 44

In [8]:
sorted(all_genres)

['Action',
 'Adventure',
 'Cars',
 'Comedy',
 'Dementia',
 'Demons',
 'Drama',
 'Ecchi',
 'Fantasy',
 'Game',
 'Harem',
 'Hentai',
 'Historical',
 'Horror',
 'Josei',
 'Kids',
 'Magic',
 'Martial Arts',
 'Mecha',
 'Military',
 'Music',
 'Mystery',
 'Parody',
 'Police',
 'Psychological',
 'Romance',
 'Samurai',
 'School',
 'Sci-Fi',
 'Seinen',
 'Shoujo',
 'Shoujo Ai',
 'Shounen',
 'Shounen Ai',
 'Slice of Life',
 'Space',
 'Sports',
 'Super Power',
 'Supernatural',
 'Thriller',
 'Unknown',
 'Vampire',
 'Yaoi',
 'Yuri']

In [9]:
genre_df = pd.DataFrame(
    sorted(all_genres),
    columns=["genre_name"]
)

genre_df.head()

  genre_name
0     Action
1  Adventure
2       Cars
3     Comedy
4   Dementia

In [10]:
genre_df.to_csv(
    "../dataset/clean_genres.csv",
    index=False
)

print("Genre list saved successfully!")

Genre list saved successfully!

In [11]:
print("Anime Count :", len(df))
print("Genre Count :", len(genre_df))

Anime Count : 12294
Genre Count : 44

In [12]:
print("Duplicate Anime IDs :", df["anime_id"].duplicated().sum())
print("Duplicate Titles :", df["name"].duplicated().sum())

Duplicate Anime IDs : 0
Duplicate Titles : 2

In [13]:
df.to_csv(
    "../dataset/clean_anime.csv",
    index=False
)

print("Clean Anime Dataset Saved!")

Clean Anime Dataset Saved!